feat : 레이싱게임 정보 엔티티,서비스로직,api 개발, 테스트코드 작성 + 레디스 도입
softeerbootcamp4th/Team3-Caecae-BE pull request #17
Opened 2024-08-05 15:23 UTC by j2noo

## 📝 작업내용
 - `RacingGameInfo` 엔티티를 만들고, 레디스의 `RedisTemplate`으로 적용하였다
 - 'racingGameInfo` 라는 키 이름으로 가지는 해시 자료구조이다.
 - `LocalDateTime`이JSON으로 직렬/역직렬화 되지 않아서 관련 설정을 추가하였음
 - 레이싱게임정보 등록/조회/시작여부 판별하는 서비스로직 및 api 개발
 - `Mockito`를 이용한 단위테스트 작성!

## 💬 침고사항
- 

## 📖 레퍼런스
- 단위테스트 코드 작성 : https://velog.io/@suzhanlee/%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C-%EC%9E%91%EC%84%B1%EB%B2%95Mockito
- Redis에서 JSON 직렬화 관련 : https://hu-bris.tistory.com/177

2024-08-05 15:26 UTC, j2noo commented
어쩌다보니 커밋이 400줄..ㅎ  테스트코드가 한 100줄쯤 되고 PR단위를 줄여보도록 하겠음~

2024-08-06 04:56 UTC, putdata requested changes

2024-08-06 04:56 UTC, putdata commented on src/main/java/ai/softeer/caecae/global/dto/response/SuccessResponse.java
> +    // 성공 관련 정보,  반환 데이터를 파라미터로 받는 생성자
반환 데이터를 파라미터로 받는 생성자 요 문구는 복붙하면서 생긴..?

2024-08-06 04:56 UTC, putdata commented on src/main/java/ai/softeer/caecae/racinggame/repository/RacingGameInfoRepository.java
> +
빈라인

2024-08-06 05:58 UTC, j2noo reviewed
리뷰에 남긴 블로그 한번 읽어보고, `dto`와 `entity`에서 빌더패턴과 롬복생성자를 사용하는 이유를 같이 공부해봅시다

2024-08-06 05:58 UTC, j2noo commented on src/main/java/ai/softeer/caecae/racinggame/service/RacingGameInfoService.java
> +@RequiredArgsConstructor(access = AccessLevel.PROTECTED)
제가 잘못 사용했네요.
엔티티에 @Builder를 사용할 때 기본 생성자를 생성하되, 무분별한 생성자를 막기 위해
`@NoArgsConstrutor(access = AccessLevel.PROTECTED)`를 사용하는게 맞는 방식인데, 전혀 엉뚱한 곳에 달아버렸네요. 수정하겠습니다.
아래 글도 읽으면 좋을 것 같아요

https://cobbybb.tistory.com/14
https://jaehoney.tistory.com/287

2024-08-06 05:58 UTC, j2noo commented on src/main/java/ai/softeer/caecae/global/dto/response/SuccessResponse.java
> +    // 성공 관련 정보,  반환 데이터를 파라미터로 받는 생성자
수정하겠읍니다

2024-08-06 06:00 UTC, j2noo commented
https://velog.io/@kevin_/%EB%82%B4%EA%B0%80-NoargsConstructor-access-AccessLevel.PROTECTED%EB%A5%BC-%EC%99%9C-%EC%9E%91%EC%84%B1%ED%96%88%EC%9D%84%EA%B9%8C

2024-08-06 06:09 UTC, putdata approved these changes
nice

2024-08-06 06:09 UTC, merged